# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://shreypandit.github.io/
baseurl:
title: Shrey Pandit
author: Shrey Pandit
description: Personal blog and resume
avatar: logo.jpg
email: pandit.shrey.01@gmail.com
github: ShreyPandit # username
#twitter: username
linkedin: shreypandit
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
